apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: hub-pod
        {{ if .Values.hub.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.proxy.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/hub/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
    spec:
      volumes:
      - name: config
        configMap:
          name: hub-config
      - name: secret
        secret:
          secretName: hub-secret
      {{ if eq .Values.hub.db.type "sqlite-pvc" }}
      - name: hub-db-dir
        persistentVolumeClaim:
          claimName: hub-db-dir
      {{- end }}
      {{- if .Values.hub.rbac.enabled }}
      serviceAccountName: hub
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.hub.uid }}
        fsGroup: {{ .Values.hub.fsGid }}
      containers:
      - name: hub-container
        image: {{ .Values.hub.image.name }}:{{ .Values.hub.image.tag }}
        volumeMounts:
          - mountPath: /etc/jupyterhub/config/
            name: config
          - mountPath: /etc/jupyterhub/secret/
            name: secret
        {{ if eq .Values.hub.db.type "sqlite-pvc" }}
          - mountPath: /srv/jupyterhub
            name: hub-db-dir
            {{ if .Values.hub.db.pvc.subPath -}}
            subPath: {{ .Values.hub.db.pvc.subPath | quote }}
            {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.hub.resources | indent 12}}
        imagePullPolicy: {{ .Values.hub.imagePullPolicy }}
        env:
        # Put this here directly so hub will restart when we
        # change this
        - name: SINGLEUSER_IMAGE
          value:  "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"
        {{ if .Values.hub.cookieSecret }}
        - name: JPY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: hub.cookie-secret
        {{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{ range $key, $value := .Values.hub.extraEnv -}}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{ end -}}
        ports:
          - containerPort: 8081
            name: hub
