hub:
  service:
    type: ClusterIP
  baseUrl: "/"
  cookieSecret: null
  rbac:
    enabled: false
  publicURL: null
  uid: 1000
  fsGid: 1000
  concurrentSpawnLimit: 64
  db:
    type: sqlite-pvc
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath: null
      storageClassName: null
    url: null
  labels: {}
  extraConfig: ""
  extraConfigMap: {}
  extraEnv: {}
  image:
    name: jupyterhub/k8s-hub
    tag: veadcd78
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  services: {}
  imagePullPolicy: IfNotPresent
  whitelist:
    users: null

proxy:
  service:
    type: LoadBalancer
    labels: {}
    annotations: {}
    nodePort: null
  image:
    name: traefik
    tag: 1.3.3
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  labels: null
  imagePullPolicy: IfNotPresent

ingress:
  enabled: false
  https:
    enabled: false
    type: none


# Google OAuth secrets
auth:
  type: dummy
  dummy:
    password: null

singleuser:
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks: null
  uid: 1000
  fsGid: 1000
  storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName: null
      subPath: "{username}"
    capacity: 10Gi
    homeMountPath: /home/jovyan
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: veadcd78
  cpu:
    limit: null
    guarantee: null
  memory:
    limit: null
    guarantee: 1G
  cmd: jupyterhub-singleuser

prePuller:
  enabled: true
  image:
    name: yuvipanda/image-allnodes-puller
    tag: v0.8

cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600

admin:
  access: true
  users: null
